#PRUEBA T DE DIFERENCIA DE MEDIAS DE ALTO Y BAJO RENDIMIENTO


#PRUEBA T DE DIFERENCIAS DE MEDIAS CON ESTUDIANTES DE ALTO RENDIMIENTO EN BASE AL HORARIO TOMADO


#PRUEBA T DE DIFERENCIAS DE MEDIAS CON ESTUDIANTES DE BAJO RENDIMIENTO EN BASE AL HORARIO TOMADO